apiVersion: v1
kind: ConfigMap
metadata:
  name: employee
data:
  spring.cloud.kubernetes.discovery.all-namespaces: "true"
  spring.data.mongodb.database: "employee"
  spring.data.mongodb.host: "mongodb.default"