apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee
  labels:
    app: employee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
        - name: employee
          image: shinyay/spring-employee-svc:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      serviceAccountName: cluster-reader
---
apiVersion: v1
kind: Service
metadata:
  name: employee-svc
  labels:
    app: employee
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: employee
#  type: NodePort
---
# For KIND
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: employee-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: employee-svc
              servicePort: 8080