apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-reader-role
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["pods", "configmaps", "services", "endpoints", "secrets"]
    verbs: ["get", "watch", "list"]
