apiVersion: apps/v1
kind: Deployment
metadata:
  name: department
  labels:
    app: department
spec:
  replicas: 1
  selector:
    matchLabels:
      app: department
  template:
    metadata:
      labels:
        app: department
    spec:
      containers:
        - name: department
          image: shinyay/spring-department-svc:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      serviceAccountName: cluster-reader
---
apiVersion: v1
kind: Service
metadata:
  name: department-svc
  labels:
    app: department
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: department
#  type: NodePort
---
# For KIND
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: department-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: department-svc
              servicePort: 8080